export const RoutePaths = {
  HOME: '/',
  SIGNUP: '/sign-up',
  LEADERBOARD: '/leaderboard',
  LOGIN: '/sign-in',
  FORGETPASSWORD: '/forgot-password',
  RESETPASSWORD: '/reset-password',
  SETPASSWORD: '/set-password',
  RESENDRESETPASSWORDEMAIL: '/resend-reset-password-email',
  RESENDVERIFICATIONEMAIL: '/resend-verification-email',
  VERIFYEMAIL: '/verify-email',
  PASSWORDCHANGESUCCESSFUL: '/password-change-successful',
  VERIFYTRANSACTION: '/verify-transaction',
  SHOWCASEROUTE: '/show-case-route/abc/123',
  NOT_FOUND: '*',
};

export const ProtectedRoutePaths = {
  USERHOME: '/dashboard',
  USERACCOUNT: '/dashboard/account',
  ALLINVESTMENTPACKAGES: '/dashboard/investments',
  ANINVESTMENTPACKAGE: '/dashboard/investments/:investmentId',
  INVESTMENTPERFORMANCES: '/dashboard/investments/performances',
  ANINVESTMENTPERFORMANCES: '/dashboard/investments/performances/:investmentId',
  CREATEINVESTMENTPACKAGES: '/dashboard/investments/create',
  PAYMENTPAGE: '/dashboard/investments/payment',
  NOTIFICATIONS: '/dashboard/notifications',
  ANOTIFICATION: '/dashboard/notifications/:notificationId',
  SERVICES: '/dashboard/services',
  ASERVICE: '/dashboard/services/:serviceId',
  REQUESTLOGS: '/dashboard/services/requests',
  WALLET: '/dashboard/wallet',
  INVESTORSTOP10: '/dashboard/investors/top-10',
  PAYOUTSCHEDULE: '/dashboard/payout/schedule',
};

export const CLientRoutPaths = {
  CLIENTHOME: '/client/dashboard/services',
  LOGISTICSSERVICES: '/client/dashboard/logistics-services',
  LOANS: '/client/dashboard/loans',
  GASSUPPLY: '/client/dashboard/gas-supply',
  REQUESTLOGS: '/client/dashboard/requests',
  CLIENTSETTINGS: '/client/dashboard/client/settings',
  REQUESTINFO: '/client/dashboard/requests/:type/:id',
  REQUESTPAYMENTLOGS: '/client/dashboard/requests-payments',
  REQUESTPAYMENTINFO: '/client/dashboard/requests-payments/:id',
};

export const AdminProtectedPaths = {
  ADMINDASHBOARD: '/admin/dashboard',
  ACTIVITYLOGS: '/admin/dashboard/activities',
  INVESTORS: '/admin/dashboard/investors',
  ALLINVESTMENTS: '/admin/dashboard/investments',
  ALLREQUESTS: '/admin/dashboard/requests',
  VIEWREQUESTDETAILS: '/admin/dashboard/requests/:id',
  ADDINVESTMENT: '/admin/dashboard/investment/add',
  VIEWINVESTMENT: '/admin/dashboard/investment/view/:id',
  ALLSTAFFS: '/admin/dashboard/staffs',
  ADDSTAFFS: '/admin/dashboard/staffs/add',
  PAYMENT: '/admin/dashboard/payment',
  PAYMENTDETAILS: '/admin/dashboard/payment/:id',
  ASTAFF: '/admin/dashboard/staffs/:id',
  UPDATESTAFF: '/admin/dashboard/staffs/:id/update',
};
