export const TOGGLESIDEBAR = 'TOGGLESIDEBAR';
export const TOGGLEPROFILESETTINGSSIDEBAR = 'TOGGLEPROFILESETTINGSSIDEBAR';
export const CLOSEMODAL = 'CLOSEMODAL';
export const OPENMODAL = 'OPENMODAL';
export const OPENSIGNINPAGE = 'OPENSIGNINPAGE';
export const OPENSIGNUPPAGE = 'OPENSIGNUPPAGE';
export const SHOWONLYMENUICONS = 'SHOWONLYMENUICONS';
export const OPENSIDEMENU = 'OPENSIDEMENU';
export const SETSIDEMENUDATA = 'SETSIDEMENUDATA';
export const CLOSESIDEMENU = 'CLOSESIDEMENU';
export const GOTOPREVIOUSSIDEMENU = 'GOTOPREVIOUSSIDEMENU';
export const ADJUSTSIDEMENUPOSITION = 'ADJUSTSIDEMENUPOSITION';
export const SETACTIVEPACKAGETAB = 'SETACTIVEPACKAGETAB';

export const GETAPPREPORTSREQUEST = 'GETAPPREPORTSREQUEST';
export const GETAPPREPORTSSUCCESS = 'GETAPPREPORTSSUCCESS';
export const GETAPPREPORTSFAILURE = 'GETAPPREPORTSFAILURE';

export const WAITLISTFORM = 'WAITLISTFORM';
export const WAITLISTFORMSUCCESSFUL = 'WAITLISTFORMSUCCESSFUL';

export const LEADERBOARDDATA = 'LEADERBOARDDATA';
export const LEADERBOARDDATASUCCESSFUL = 'LEADERBOARDDATASUCCESSFUL';

export const OPENSUCCESSMODAL = 'OPENSUCCESSMODAL';

export const USERROLES = 'userroles';
export const PACKAGETYPES = 'packagetypes';
export const REQUESTTYPES = 'requesttypes';
export const REQUESTSTATUSES = 'requeststatues';
export const PACKAGESTATUSES = 'packagestatues';
export const USERSTATUSES = 'userstatues';
