export const SIGNINREQUEST = 'SIGNINREQUEST';
export const SIGNINSUCCESS = 'SIGNINSUCCESS';
export const SIGNINFAILURE = 'SIGNINFAILURE';

export const SIGNUPREQUEST = 'SIGNUPREQUEST';
export const SIGNUPSUCCESS = 'SIGNUPSUCCESS';
export const SIGNUPFAILURE = 'SIGNUPFAILURE';

export const CONFIRMEMAILREQUEST = 'CONFIRMEMAILREQUEST';
export const CONFIRMEMAILSUCCESS = 'CONFIRMEMAILSUCCESS';
export const CONFIRMEMAILFAILURE = 'CONFIRMEMAILFAILURE';

export const FORGOTPASSWORDREQUEST = 'FORGOTPASSWORDREQUEST';
export const FORGOTPASSWORDSUCCESS = 'FORGOTPASSWORDSUCCESS';
export const FORGOTPASSWORDFAILURE = 'FORGOTPASSWORDFAILURE';

export const RESETPASSWORDREQUEST = 'RESETPASSWORDREQUEST';
export const RESETPASSWORDSUCCESS = 'RESETPASSWORDSUCCESS';
export const RESETPASSWORDFAILURE = 'RESETPASSWORDFAILURE';

export const CHANGEPASSWORDREQUEST = 'CHANGEPASSWORDREQUEST';
export const CHANGEPASSWORDSUCCESS = 'CHANGEPASSWORDSUCCESS';
export const CHANGEPASSWORDFAILURE = 'CHANGEPASSWORDFAILURE';

export const RESENDVERIFICATIONMAILREQUEST = 'RESENDVERIFICATIONMAILREQUEST';
export const RESENDVERIFICATIONMAILSUCCESS = 'RESENDVERIFICATIONMAILSUCCESS';
export const RESENDVERIFICATIONMAILFAILURE = 'RESENDVERIFICATIONMAILFAILURE';

export const LOGOUTREQUEST = 'LOGOUTREQUEST';
