export const GETCLIENTVERIFICATIONREQUEST = 'GETCLIENTVERIFICATIONREQUEST';
export const GETCLIENTVERIFICATIONSUCCESSFUL = 'GETCLIENTVERIFICATIONSUCCESSFUL';
export const GETCLIENTVERIFICATIONFAILURE = 'GETCLIENTVERIFICATIONFAILURE';
