export const ADDPACKAGEREQUEST = 'ADDPACKAGEREQUEST';
export const ADDPACKAGESUCCESSFUL = 'ADDPACKAGESUCCESSFUL';
export const ADDPACKAGEFAILURE = 'ADDPACKAGEFAILURE';

export const GETPACKAGEREQUEST = 'GETPACKAGEREQUEST';
export const GETPACKAGESUCCESSFUL = 'GETPACKAGESUCCESSFUL';
export const GETPACKAGEFAILURE = 'GETPACKAGEFAILURE';

export const GETAPACKAGEINFOREQUEST = 'GETAPACKAGEINFOREQUEST';
export const GETAPACKAGEINFOSUCCESSFUL = 'GETAPACKAGEINFOSUCCESSFUL';
export const GETAPACKAGEINFOFAILURE = 'GETAPACKAGEINFOFAILURE';

export const GETPACKAGECREATEDBYCURRENTUSERREQUEST = 'GETPACKAGECREATEDBYCURRENTUSERREQUEST';
export const GETPACKAGECREATEDBYCURRENTUSERSUCCESSFUL = 'GETPACKAGECREATEDBYCURRENTUSERSUCCESSFUL';
export const GETPACKAGECREATEDBYCURRENTUSERFAILURE = 'GETPACKAGECREATEDBYCURRENTUSERFAILURE';

export const UPDATEPACKAGEREQUEST = 'UPDATEPACKAGEREQUEST';
export const UPDATEPACKAGESUCCESSFUL = 'UPDATEPACKAGESUCCESSFUL';
export const UPDATEPACKAGEFAILURE = 'UPDATEPACKAGEFAILURE';

export const DELETEPACKAGEREQUEST = 'DELETEPACKAGEREQUEST';
export const DELETEPACKAGESUCCESSFUL = 'DELETEPACKAGESUCCESSFUL';
export const DELETEPACKAGEFAILURE = 'DELETEPACKAGEFAILURE';

export const OTHERACTIONPACKAGEREQUEST = 'OTHERACTIONPACKAGEREQUEST';
export const OTHERACTIONPACKAGESUCCESSFUL = 'OTHERACTIONPACKAGESUCCESSFUL';
export const OTHERACTIONPACKAGEFAILURE = 'OTHERACTIONPACKAGEFAILURE';

export const GETPAYOUTSCHEDULEREQUEST = 'GETPAYOUTSCHEDULEREQUEST';
export const GETPAYOUTSCHEDULESUCCESSFUL = 'GETPAYOUTSCHEDULESUCCESSFUL';
export const GETPAYOUTSCHEDULEFAILURE = 'GETPAYOUTSCHEDULEFAILURE';

export const USERPACKAGECATEGORY = {
  Completed: 'completed',
  Deleted: 'deleted',
  Active: 'active',
  Explore: 'explore',
  Growing: 'growing',
};
