export const ADDREQUESTREQUEST = 'ADDREQUESTREQUEST';
export const ADDREQUESTSUCCESSFUL = 'ADDREQUESTSUCCESSFUL';
export const ADDREQUESTFAILURE = 'ADDREQUESTFAILURE';

export const GETREQUESTREQUEST = 'GETREQUESTREQUEST';
export const GETREQUESTSUCCESSFUL = 'GETREQUESTSUCCESSFUL';
export const GETREQUESTFAILURE = 'GETREQUESTFAILURE';

export const GETAREQUESTINFOREQUEST = 'GETAREQUESTINFOREQUEST';
export const GETAREQUESTINFOSUCCESSFUL = 'GETAREQUESTINFOSUCCESSFUL';
export const GETAREQUESTINFOFAILURE = 'GETAREQUESTINFOFAILURE';

export const GETREQUESTCREATEDBYCURRENTUSERREQUEST = 'GETREQUESTCREATEDBYCURRENTUSERREQUEST';
export const GETREQUESTCREATEDBYCURRENTUSERSUCCESSFUL = 'GETREQUESTCREATEDBYCURRENTUSERSUCCESSFUL';
export const GETREQUESTCREATEDBYCURRENTUSERFAILURE = 'GETREQUESTCREATEDBYCURRENTUSERFAILURE';

export const UPDATEREQUESTREQUEST = 'UPDATEREQUESTREQUEST';
export const UPDATEREQUESTSUCCESSFUL = 'UPDATEREQUESTSUCCESSFUL';
export const UPDATEREQUESTFAILURE = 'UPDATEREQUESTFAILURE';

export const DELETEREQUESTREQUEST = 'DELETEREQUESTREQUEST';
export const DELETEREQUESTSUCCESSFUL = 'DELETEREQUESTSUCCESSFUL';
export const DELETEREQUESTFAILURE = 'DELETEREQUESTFAILURE';

export const OTHERACTIONREQUESTREQUEST = 'OTHERACTIONREQUESTREQUEST';
export const OTHERACTIONREQUESTSUCCESSFUL = 'OTHERACTIONREQUESTSUCCESSFUL';
export const OTHERACTIONREQUESTFAILURE = 'OTHERACTIONREQUESTFAILURE';
