export const GETUSERSTATISTICSREQUESTS = 'GETUSERSTATISTICSREQUESTS';
export const GETUSERSTATISTICSSUCCESSFUL = 'GETUSERSTATISTICSSUCCESSFUL';
export const GETUSERSTATISTICSFAILURE = 'GETUSERSTATISTICSFAILURE';

export const GETADMINSTATISTICSREQUESTS = 'GETADMINSTATISTICSREQUESTS';
export const GETADMINSTATISTICSSUCCESSFUL = 'GETADMINSTATISTICSSUCCESSFUL';
export const GETADMINSTATISTICSFAILURE = 'GETADMINSTATISTICSFAILURE';

export const GETAUDITTAILSREQUESTS = 'GETAUDITTAILSREQUESTS';
export const GETAUDITTAILSSUCCESSFUL = 'GETAUDITTAILSSUCCESSFUL';
export const GETAUDITTAILSFAILURE = 'GETAUDITTAILSFAILURE';
