export const GETUSERSUBSCRIPTIONSREQUESTS = 'GETUSERSUBSCRIPTIONSREQUESTS';
export const GETUSERSUBSCRIPTIONSSUCCESSFUL = 'GETUSERSUBSCRIPTIONSSUCCESSFUL';
export const GETUSERSUBSCRIPTIONSFAILURE = 'GETUSERSUBSCRIPTIONSFAILURE';

export const CREDITORDEBITUSERREQUESTS = 'CREDITORDEBITUSERREQUESTS';
export const CREDITORDEBITUSERSUCCESSFUL = 'CREDITORDEBITUSERSUCCESSFUL';
export const CREDITORDEBITUSERFAILURE = 'CREDITORDEBITUSERFAILURE';

export const TRANSACTION = {
  CREDIT: 'credit',
  DEBIT: 'debit',
};

export const CLEARINITIATEWITHDRAWALDATA = 'CLEARINITIATEWITHDRAWALDATA';

// export const GETAUDITTAILSREQUESTS = 'GETAUDITTAILSREQUESTS';
// export const GETAUDITTAILSSUCCESSFUL = 'GETAUDITTAILSSUCCESSFUL';
// export const GETAUDITTAILSFAILURE = 'GETAUDITTAILSFAILURE';
