export const GETAUTHUSERDATAREQUEST = 'GETAUTHUSERDATAREQUEST';
export const GETAUTHUSERDATASUCCESS = 'GETAUTHUSERDATASUCCESS';
export const GETAUTHUSERDATAFAILURE = 'GETAUTHUSERDATAFAILURE';

export const GETAUTHUSERSETTINGSDATAREQUEST = 'GETAUTHUSERSETTINGSDATAREQUEST';
export const GETAUTHUSERSETTINGSDATASUCCESS = 'GETAUTHUSERSETTINGSDATASUCCESS';
export const GETAUTHUSERSETTINGSDATAFAILURE = 'GETAUTHUSERSETTINGSDATAFAILURE';

export const CREATEUSERREQUEST = 'CREATEUSERREQUEST';
export const CREATEUSERSUCCESS = 'CREATEUSERSUCCESS';
export const CREATEUSERFAILURE = 'CREATEUSERFAILURE';

export const UPDATEPROFILEINPUTFIELDS = 'UPDATEPROFILEINPUTFIELDS';

export const UPDATEUSERPROFILEDETAILSREQUEST = 'UPDATEUSERPROFILEDETAILSREQUEST';
export const UPDATEUSERPROFILEDETAILSSUCCESS = 'UPDATEUSERPROFILEDETAILSSUCCESS';
export const UPDATEUSERPROFILEDETAILSFAILURE = 'UPDATEUSERPROFILEDETAILSFAILURE';
export const USERLOGOUT = 'USERLOGOUT';
export const SETUSERROLE = 'SETUSERROLE';

export const GETNOTIFICATIONREQUEST = 'GETNOTIFICATIONREQUEST';
export const GETNOTIFICATIONSUCCESS = 'GETNOTIFICATIONSUCCESS';
export const GETNOTIFICATIONFAILURE = 'GETNOTIFICATIONFAILURE';

export const MARKALLNOTIFICATIONASREADREQUEST = 'MARKALLNOTIFICATIONASREADREQUEST';
export const MARKALLNOTIFICATIONASREADSUCCESS = 'MARKALLNOTIFICATIONASREADSUCCESS';
export const MARKALLNOTIFICATIONASREADFAILURE = 'MARKALLNOTIFICATIONASREADFAILURE';

export const GETUSERBYUSERNAMEREQUEST = 'GETUSERBYUSERNAMEREQUEST';
export const GETUSERBYUSERNAMESUCCESS = 'GETUSERBYUSERNAMESUCCESS';
export const GETUSERBYUSERNAMEFAILURE = 'GETUSERBYUSERNAMEFAILURE';

export const GETALLUSERSREQUEST = 'GETALLUSERSREQUEST';
export const GETALLUSERSSUCCESS = 'GETALLUSERSSUCCESS';
export const GETALLUSERSFAILURE = 'GETALLUSERSFAILURE';

export const ACTONUSERREQUEST = 'ACTONUSERREQUEST';
export const ACTONUSERSUCCESS = 'ACTONUSERSUCCESS';
export const ACTONUSERFAILURE = 'ACTONUSERFAILURE';

export const DELETEUSERREQUEST = 'DELETEUSERREQUEST';
export const DELETEUSERSUCCESS = 'DELETEUSERSUCCESS';
export const DELETEUSERFAILURE = 'ACTONUSERFAILURE';

export const GETUSERWALLETREQUEST = 'GETUSERWALLETREQUEST';
export const GETUSERWALLETSUCCESS = 'GETUSERWALLETSUCCESS';
export const GETUSERWALLETFAILURE = 'GETUSERWALLETFAILURE';

export const SUPERADMIN = 'SuperAdmin';
export const ADMIN = 'Admin';
export const ClIENTUSER = 'Client';
export const INVESTORUSER = 'Investor';
export const NONE = 'None';
export const ACTIVATE = 'active';
export const SUSPEND = 'suspend';
export const BLACKLIST = 'blacklist';
